/* ==========================================================================
 * 词库 2/4：筛选面板与属性值
 * 这批是命中率最高的（浏览页筛选器几乎每一页都出现）
 * ========================================================================== */

var DICT_FILTERS = {

  /* ------------------------------------------------------ 筛选器标题 */
  'Vibe': '氛围',
  'Type': '类型',
  'Style': '风格',
  'Graphics': '画面',
  'Technique': '技法',
  'Movement': '动态',
  'Subject': '主体',
  'Product Type': '商品类型',
  'Service Type': '服务类型',
  'Content Rating': '内容分级',
  'Art Style': '画风',
  'Compatible with': '兼容',

  /* ---------------------------------------------------------- 氛围 */
  'Angry / Aggressive': '愤怒／激烈',
  'Chill / Cozy': '慵懒／治愈',
  'Cute / Sweet': '可爱／甜美',
  'Dark / Mysterious': '暗黑／神秘',
  'Dramatic / Emotional': '戏剧／情感',
  'Epic / Powerful': '史诗／力量',
  'Funny / Quirky': '搞笑／古怪',
  'Futuristic / Sci-fi': '未来／科幻',
  'Happy / Cheerful': '快乐／开朗',
  'Minimal / Clean': '极简／干净',
  'Relaxing / Peaceful': '放松／宁静',
  'Romantic / Feeling': '浪漫／抒情',
  'Sad / Somber': '悲伤／阴郁',
  'Scary / Horror': '恐怖／惊悚',
  'Upbeat / Energetic': '欢快／活力',

  /* ---------------------------------------------------------- 风格 */
  'Abstract': '抽象',
  'Anime / Manga': '日式动漫',
  '90s Anime / Manga': '90 年代动漫',
  'Cartoon': '美式卡通',
  'Manhwa / Manhua': '韩漫／国漫',
  'Meme': '梗图',
  'Semi-realistic': '半写实',
  'Doodle / Sketch': '涂鸦／速写',
  'Flat color / Cel-shaded': '平涂／赛璐璐',
  'Lineless': '无线稿',
  'Monochrome': '单色',
  'Painted / Rendered': '厚涂／渲染',
  'Pixel Art': '像素风',
  'Retro / Vintage': '复古',
  'Minimalistic': '极简',

  /* ---------------------------------------------------------- 画面 */
  '3D Render': '3D 渲染',
  'Computer graphics': '电脑图形',
  'Computer animated graphics': '电脑动画图形',
  '2D Animation': '2D 动画',
  '3D Animation': '3D 动画',
  'Animated 3D models': '动画 3D 模型',
  'Animation': '动画',
  'Motion Graphics': '动态图形',
  'Illustrated': '插画',
  'Illustrated frame-by-frame': '插画逐帧',
  'Frame by frame': '逐帧',
  'Frame-by-frame': '逐帧',
  'Rigged + animated illustrations': '绑定 + 动画插画',

  /* ---------------------------------------------------------- 技法 */
  'Hand-drawn': '手绘',
  'Vector': '矢量',
  'Tileable': '可平铺',
  'Looped': '循环',
  'Not looped': '不循环',

  /* ---------------------------------------------------------- 动态 */
  'Animated': '有动画',
  'Static': '静态',
  'Movement included': '含动作',
  'Not made to move': '不可动',
  'Animation-ready': '可制作动画',
  'Cut + layered only': '仅切层',
  'Ready for movement': '可做动作',
  'Rigged': '已绑定',
  'Rigged movement icon': '已绑定动态图标',
  'Animated movement icon': '动画动态图标',
  'Cut movement icon': '切层动态图标',
  'Static movement icon': '静态动态图标',
  'Play video icon': '播放视频图标',

  /* ---------------------------------------------------------- 水平 */
  'Novice': '新手',
  'Intermediate': '中级',
  'Advanced': '高级',
  'Experienced': '资深',

  /* ---------------------------------------------------------- 主体 */
  '100% human': '纯人类',
  'Anthro / Furry': '兽人／福瑞',
  'Ears / tail / etc': '兽耳／尾巴等',
  'Face ≠ human': '非人类面孔',
  'Human': '人类',
  'Human-like': '类人',
  'Robot / Mecha': '机器人／机甲',
  'Robotronic': '机械体',
  'Animal': '动物',
  'Creature': '生物',
  'Monster': '怪物',

  /* ---------------------------------------------------------- 特征 */
  'Closed Species': '封闭物种',
  'Elderly': '老年',
  'Female': '女性',
  'Male': '男性',
  'Non-binary': '非二元',
  'Female Voice': '女声',
  'Male Voice': '男声',
  'Gender Neutral Voice': '中性声线',

  /* ------------------------------------------------------ 敏感内容 */
  'Artistic nudity': '艺术裸体',
  'Blood': '血腥',
  'Flashing / epilepsy warning': '闪烁／癫痫警告',
  'Gore / heavy violence (18+)': '血腥／重度暴力（18+）',
  'Revealing clothes': '暴露衣着',
  'Sexual nudity (18+)': '性裸体（18+）',
  'Sexually suggestive (18+)': '性暗示（18+）',
  'Non-sexual': '非性相关',
  'NDA required (privacy fee)': '需签保密协议（隐私费）',
  'Not while WIP but final work is ok': '进行中不可，完成稿可以',

  /* ---------------------------------------------------------- 方向 */
  'Horizontal': '横向',
  'Vertical': '纵向',
  'Landscape': '横版',
  'Portrait': '竖版',
  'Single Screen': '单屏',
  'Vertical Scroll': '纵向滚动',
  'Traditional Page': '传统翻页',

  /* ---------------------------------------------------------- 节奏 */
  'Slow': '慢',
  'Fast': '快',

  /* ---------------------------------------------------------- 时长 */
  'Very short': '极短',
  'Very Long': '极长',
  'Short': '短',
  'Long': '长',
  'Micro': '微型',
  'Under 1 min': '1 分钟内',
  '1-2 min': '1-2 分钟',
  '2-6 min': '2-6 分钟',
  'Over 6 min': '6 分钟以上',
  'Under 10 min': '10 分钟内',
  '10-30 min': '10-30 分钟',
  'Over 30 min': '30 分钟以上',
  '0 - 0.5 hrs': '0 - 0.5 小时',
  '0 - 2 hrs': '0 - 2 小时',
  '0.5 - 1 hr': '0.5 - 1 小时',
  '1 - 3 hr': '1 - 3 小时',
  '3 - 5 hr': '3 - 5 小时',
  '2 - 5 hrs': '2 - 5 小时',
  '5 - 10 hrs': '5 - 10 小时',
  '10 - 20 hrs': '10 - 20 小时',
  '20+ hrs': '20 小时以上',
  '5+ hrs': '5 小时以上',
  '8+ characters': '8 个以上角色',

  /* ---------------------------------------------------------- 语言 */
  'Chinese': '中文',
  'English': '英语',
  'French': '法语',
  'German': '德语',
  'Indonesian': '印尼语',
  'Japanese': '日语',
  'Korean': '韩语',
  'Spanish': '西班牙语',

  /* ------------------------------------------------------ 性别 / 人群 */
  'Everyone': '所有人',
  'Gamer': '游戏玩家',
  'Content Creator': '内容创作者',
  'Group account': '团体账号',
  'Individual': '个人',
  'Studio': '工作室',
  'Corporate': '企业',
  'Business': '商业',

  /* ------------------------------------------------------ 版权 / 来源 */
  'Original creator': '原作者',
  'Current owner': '当前持有者',
  'Sold by': '卖家',
  'Original Designs': '原创设计',
  'Original Design': '原创设计',
  'Design': '设计',
  'Customizable': '可定制',

  /* ------------------------------------------------------ 主题 / 场景 */
  'Fantasy': '奇幻',
  'Science Fiction': '科幻',
  'Nature': '自然',
  'Urban': '都市',
  'Rural': '乡村',
  'Interior': '室内',
  'Exterior': '室外',
  'Vehicle': '载具',
  'Weapon': '武器',
  'Food': '食物',
  'Plant': '植物',
  'Object': '物品',
  'Chair': '椅子',
  'Background': '背景',
  'Backgrounds': '背景',
  'Eyes': '眼睛',
  'Hair': '头发',
  'Arms': '手臂',
  'Accessories': '配件',
  'From imagination': '想象',
  'From nightmares': '噩梦',
  'From real world': '现实',
  '1 of a kind': '独一无二',

  /* ---------------------------------------------------------- 构图 */
  'Body-only': '仅身体',
  'Head-only': '仅头部',
  'Bust Up': '半身',
  'Anime Bust Up': '动漫半身',
  'Half Body': '半身',
  'Full Body': '全身',
  'Thigh Up': '大腿以上',
  'Icon / Headshot': '图标／头像',
  'Single Image': '单张图',
  'Detailed illustration': '精细插画',
  'Low detail / abstract': '低细节／抽象',
  'None (Sprite)': '无（精灵图）',
  'Complex (Scene)': '复杂（场景）',
  'Transparent / 1 color': '透明／单色',

  /* ---------------------------------------------------------- 游戏类型 */
  'Action': '动作',
  'Adventure': '冒险',
  'Casual': '休闲',
  'Fighting': '格斗',
  'Platformer': '平台跳跃',
  'Puzzle': '解谜',
  'Racing': '竞速',
  'Rhythm': '音游',
  'Rogue-like': 'Roguelike',
  'Role playing': '角色扮演',
  'Roleplay': '角色扮演',
  'Shooter': '射击',
  'Simulation': '模拟',
  'Sports': '体育',
  'Strategy': '策略',
  'Survival': '生存',
  'Visual novel': '视觉小说',
  'Visual novel / game': '视觉小说／游戏',
  'Story-rich': '剧情丰富',
  'Card game': '卡牌游戏',

  /* ------------------------------------------------------ 交付 / 完成度 */
  'Ready to use': '可直接使用',
  'Ready for rigging': '可绑定',
  'Art-only': '仅美术',
  'Art + Rigging Combo': '美术 + 绑定组合',
  'Design only': '仅设计',
  'Design + extras': '设计 + 附加项',
  'Complete Story': '完整故事',
  'Modular': '模块化',
  'Pre-made': '预制',
  'Customizable': '可定制',

  /* ---------------------------------------------------------- 其它 */
  'All Streamers': '所有主播',
  'Misc': '杂项',
  'Other': '其他',
  'None': '无',
  'All': '全部',
  'Or': '或'
};
