/* ==========================================================================
 * 词库 5/5：零散短标签
 * 这里专门放"后补的一次性小词"，方便以后持续往里加，不用动前面几个大词库。
 * 覆盖率自测报出来的漏词，基本都补到这儿。
 * ========================================================================== */

var DICT_EXTRA = {

  /* -------------------------------------------------- 等级 / 程度类 */
  'Low': '低',
  'Medium': '中',
  'High': '高',
  'Junior': '初级',
  'Senior': '高级',
  'General': '综合',
  'Advanced': '高级',
  'Experienced': '资深',
  'Novice': '新手',

  /* ------------------------------------------------------ 身份 / 角色 */
  'User': '用户',
  'Creator': '创作者',
  'Character': '角色',
  'Characters': '角色',
  'Partner': '合作伙伴',
  'Broker': '经纪人',
  'Student': '学生',
  'Studio': '工作室',
  'Individual': '个人',
  'Corporate': '企业',
  'Business': '商业',
  'Group account': '团体账号',

  /* ---------------------------------------------------------- 内容 */
  'Demo': '演示',
  'Logo': '标志',
  'Lore': '世界观',
  'Love': '爱情',
  'Life': '生活',
  'Family': '家庭',
  'Friends': '朋友',
  'Reading': '阅读',
  'Social': '社交',
  'Network': '网络',
  'System': '系统',
  'Audio': '音频',
  'Event': '活动',
  'Image': '图片',
  'Render': '渲染',
  'Chapter': '章节',
  'Crop': '裁剪',
  'Timing': '时序',
  'Furry': '福瑞',
  'Fashion': '时尚',
  'Patterns': '图案',
  'Microphone': '麦克风',
  'Productivity': '效率',
  'Signature': '签名',
  'Milestone': '里程碑',
  'Timelapse': '延时摄影',
  'Showcase': '展示',
  'Selling': '出售中',
  'Tablet': '平板',
  'Browser-based': '浏览器端',
  'Standee': '立牌',
  'Standees': '立牌',
  'Interaction': '互动',
  'Review': '评价',
  'Rating': '评分',
  'Report': '举报',
  'Share': '分享',
  'Overview': '概览',
  'Details': '详情',
  'Description': '描述',
  'Deliverables': '交付物',
  'Reference': '参考',
  'Arts': '美术',
  'Art': '美术',
  'Assets': '素材',
  'Templates': '模板',
  'Theme': '主题',
  'Themes': '主题',
  'Sprite': '精灵图',
  'Sprites': '精灵图',
  'Overlay': '叠加层',
  'Overlays': '叠加层',
  'Badge': '徽章',
  'Sticker': '贴纸',
  'Wallpaper': '壁纸',
  'Cursor': '指针',
  'Cursors': '指针',
  'Icon': '图标',
  'Icons': '图标',
  'Banner': '横幅',
  'Banners': '横幅',
  'Cover': '封面',
  'Thumbnail': '缩略图',
  'Thumbnails': '缩略图',
  'Trailer': '预告片',
  'Transition': '转场',
  'Transitions': '转场',
  'Widget': '挂件',
  'Widgets': '挂件',
  'Panel': '面板',
  'Panels': '面板',
  'Schedule': '排期',
  'Tuning': '调校',
  'Mastering': '母带',
  'Mixing': '混音',
  'Instrumental': '伴奏',
  'Lyrics': '歌词',
  'Vocal': '人声',
  'Voice': '声音',

  /* -------------------------------------------------------- 周边 / 实体 */
  'VG Mug': 'VG 马克杯',
  'VG Plushie': 'VG 毛绒玩具',
  'Mug': '马克杯',
  'Plushie': '毛绒玩具',
  'Figure': '手办',
  'Charm': '挂件',
  'Charms': '挂件',
  'Poster': '海报',
  'Posters': '海报',
  'Prints': '印刷品',
  'Keychain': '钥匙扣',
  'Keychains': '钥匙扣',
  'Apparel': '服饰',
  'Clothing': '服装',
  'Accessory': '配饰',

  /* ---------------------------------------------------------- 品牌标记 */
  'VGen logo': 'VGen 标志',
  'VGen Boosted icon': 'VGen 助推图标',
  'VSONA logo': 'VSONA 标志',
  'Security logo': '安全标志',
  'VG face': 'VG 表情',

  /* ---------------------------------------------------------- 杂项 */
  'About': '关于',
  'Contact': '联系',
  'Feedback': '反馈',
  'Support': '支持',
  'Terms': '条款',
  'Privacy': '隐私',
  'Language': '语言',
  'Currency': '货币',
  'Notifications': '通知',
  'Verification': '认证',
  'Unverified': '未认证',
  'Draft': '草稿',
  'Public': '公开',
  'Private': '私密',
  'Unlisted': '不公开列出',
  'Sold out': '已售罄',
  'On sale': '促销中',
  'New': '新品',
  'Featured': '精选',
  'Staff pick': '官方精选',
  'Daily': '每日',
  'Weekly': '每周',
  'Monthly': '每月',

  /* -------------------------------------------- 登录后仪表盘（从真实截图补） */
  'Dashboard': '控制台',
  'Go to my profile': '前往我的主页',
  'Wallet': '钱包',
  'Balance': '余额',
  'Earnings': '收入',
  'Payouts': '提现',
  'Payout': '提现',
  'Withdraw': '提现',
  'Quests': '需求',
  'Quest': '需求',
  'Discounts': '折扣',
  'Coupons': '优惠券',
  'Workflows': '工作流',
  'Workflow': '工作流',
  'Forms': '表单',
  'Form': '表单',
  'Policies': '政策',
  'Policy': '政策',
  'Orders': '订单',
  'Products': '商品',
  'Bundles': '套餐',
  'Bundle': '套餐',
  'Services': '服务',
  'Requests': '请求',
  'Reviews': '评价',
  'Analytics': '数据分析',
  'Insights': '数据洞察',
  'Storefront': '店铺主页',
  'Inbox': '收件箱',
  'Drafts': '草稿',
  'Archived': '已归档',
  'Archive': '归档',
  'Trash': '回收站',
  'Follow': '关注',
  'Unfollow': '取消关注',
  'Block': '屏蔽',
  'Mute': '静音',
  'Bookmark': '收藏',
  'Bookmarks': '收藏',
  'Favorite': '喜欢',
  'Favorites': '喜欢',
  'Queue': '队列',
  'Queued': '排队中',
  'In progress': '进行中',
  'Delivered': '已交付',
  'Cancelled': '已取消',
  'Canceled': '已取消',
  'Refunded': '已退款',
  'Disputed': '争议中',
  'Expired': '已过期',
  'Active': '生效中',
  'Inactive': '已停用',
  'Paused': '已暂停',
  'Scheduled': '已排期',
  'Published': '已发布',
  'Unpublished': '未发布',
  'Deleted': '已删除',
  'Upload': '上传',
  'Download': '下载',
  'Export': '导出',
  'Import': '导入',
  'Create': '创建',
  'Update': '更新',
  'Preview': '预览',
  'Duplicate': '复制一份',
  'Select': '选择',
  'Selected': '已选择',
  'Filter': '筛选',
  'Sort': '排序',
  'More': '更多',
  'Less': '收起',
  'Show more': '显示更多',
  'Show less': '收起',
  'Load more': '加载更多',
  'View all': '查看全部',
  'See all': '查看全部',
  'Learn more': '了解更多',
  'Read more': '阅读更多',
  'Back to top': '回到顶部',

  'Personalize your feed': '个性化你的信息流',
  'Customize feed': '自定义信息流',
  'Customize your feed': '自定义你的信息流',
  'For you': '为你推荐',
  'Following': '关注中',
  'Trending': '热门',
  'Random': '随机',
  'Latest': '最新',

  /* ---------------------------------------------------------- 收尾补漏 */
  'Newlywed': '新婚',
  'Video Game': '电子游戏',
  'Desktop (1080p)': '桌面（1080p）',
  'Desktop (4K)': '桌面（4K）',
  'Desktop (8K)': '桌面（8K）',
  'Phone (iOS / Android)': '手机（iOS／Android）',
  'Phone (iPad / Android)': '手机（iPad／Android）',
  'LIVE NOW ·': '直播中 ·',
  '1st stream': '首次直播',
  'App Alpha': 'App Alpha',
  'Short, vertical, memorable, and the best way to grow your following.': '短、竖版、好记，涨粉最有效的方式。'
};
