/* ==========================================================================
 * 词库 1/4：界面文案（导航、按钮、表单、状态、提示）
 * 键 = VGen 页面上的英文原文（首尾空白由引擎自动去掉）
 * 值 = 中文
 * ========================================================================== */

var DICT_UI = {

  /* ---------------------------------------------------------- 顶部导航 */
  'About us': '关于我们',
  'Explore': '探索',
  'Explore...': '探索…',
  'Discover': '发现',
  'Categories': '分类',
  'Community': '社区',
  'Challenges': '挑战',
  'Challenge': '挑战',
  'Contest': '比赛',
  'Campaigns': '活动',
  'Commissions': '委托',
  'Commission': '委托',
  'Shop': '商店',
  'Artist dashboard': '画师控制台',
  'BoothPal': 'BoothPal',
  'Messages': '消息',
  'Chat': '聊天',
  'Notifications': '通知',
  'Profile': '个人资料',
  'Portfolio': '作品集',
  'Settings': '设置',
  'Help': '帮助',
  'Get help': '获取帮助',
  'Log in': '登录',
  'Log out': '退出登录',
  'View profile': '查看主页',
  'Stage': '展示台',
  'Invites': '邀请',
  'Invite codes': '邀请码',
  'Trending': '热门',
  'Latest': '最新',
  'Random': '随机',

  /* ---------------------------------------------------------- 搜索筛选 */
  'Search': '搜索',
  'Search direct messages': '搜索私信',
  'Search for a tag, category, artist, or service': '搜索标签、分类、画师或服务',
  'Filters': '筛选',
  'Filter by price range': '按价格区间筛选',
  'Sort by:': '排序：',
  'Popular in last 24 hours': '24 小时内热门',
  'Recommended': '推荐',
  'Related': '相关',
  'Personalize your feed': '个性化你的信息流',
  'Your likes and search': '你的点赞与搜索',
  'People you follow': '你关注的人',
  'Your following’s following': '你关注的人所关注的',
  'Following': '关注中',
  'Follower': '粉丝',
  'For you': '为你推荐',
  'For you feed may take a few minutes to update': '为你推荐的信息流可能需要几分钟更新',
  'What type of service are you looking for?': '你在找什么类型的服务？',
  'I want to commission...': '我想委托……',
  'I want to shop...': '我想购物……',

  /* ---------------------------------------------------------- 购物结算 */
  'Basket': '购物车',
  'See basket': '查看购物车',
  'Start shopping': '开始购物',
  'My orders': '我的订单',
  'Order': '订单',
  'Subtotal': '小计',
  'Discount': '折扣',
  'Payment Methods': '支付方式',
  'Payment Plan': '分期付款',
  'PayPal': 'PayPal',
  'Sales tax calculated at checkout': '税费在结账时计算',
  'Digital goods': '数字商品',
  'Physical goods': '实体商品',
  'Requires shipping': '需要邮寄',
  'Immediate online delivery': '即时在线交付',
  'Nothing in your basket yet': '购物车还是空的',
  'Once you add items from a store, your basket will appear here.': '从商店添加商品后，购物车会显示在这里。',
  'Remove all items?': '移除所有商品？',

  /* ------------------------------------------------------------ 授权 */
  'Licenses': '授权',
  'Available licenses': '可用授权',
  'Choose the licenses you need.': '选择你需要的授权。',
  'VGen Standard Licenses': 'VGen 标准授权',
  'VGen licenses': 'VGen 授权',
  'Licensee': '被授权方',
  'Commercial use': '商用',
  'Non-commercial use': '非商用',
  'Personal': '个人',
  'Credit': '署名',
  'Credit the artist': '署名画师',
  'No Generative AI': '禁止生成式 AI',
  'Not allowed': '不允许',
  'Not available': '不可用',
  'As defined by individual artists': '由各画师自行定义',
  'Reselling with permission': '经许可可转售',
  'For individual, non-commercial and non-monetized uses only': '仅限个人、非商业、非盈利用途',
  'Required for all public uses unless otherwise stated': '除另有说明外，所有公开使用均需此授权',
  'Commercial: Content': '商用：内容',
  'Commercial: Merchandising': '商用：周边',
  'Digital Illustration': '数字插画',

  /* ------------------------------------------------------------ 表单 */
  'Username': '用户名',
  'Username or email': '用户名或邮箱',
  'Email': '邮箱',
  'Password': '密码',
  'Birth date': '出生日期',
  'Update your birthdate': '更新你的生日',
  'Date / time': '日期／时间',
  'Guaranteed Delivery date': '保证交付日期',
  'Account Type': '账户类型',
  'Enter Code': '输入邀请码',
  'Enter your code to skip the artist account queue': '输入邀请码可跳过画师账号排队',
  'I have an Artist Invite Code': '我有画师邀请码',
  'Unlock artist access': '解锁画师权限',
  'Become an artist+': '成为 artist+',
  'Artist+ details': 'artist+ 详情',
  'Profile Setup': '资料设置',
  'Verify your password': '验证密码',
  'Re-enter your password to continue.': '请重新输入密码以继续。',
  'Forgot password?': '忘记密码？',
  'Forgot password / don\'t have one yet?': '忘记密码／还没有密码？',
  'Lost access to your authenticator app?': '无法使用验证器应用了？',
  'Translate from': '源语言',
  'Translate to': '目标语言',
  'a message': '发条消息…',
  'Start your conversation': '开始对话',
  'Search chats': '搜索聊天',
  'Archive this chat?': '归档此聊天？',
  'Failed to load chats': '聊天加载失败',
  'Create ticket': '创建工单',
  'Report an error': '报告错误',
  'This will not be shown publicly.': '这不会公开显示。',
  'Content preferences': '内容偏好',
  'Sensitivities': '敏感内容',
  'Sensitive Content': '敏感内容',
  'Mature Content': '成人内容',
  'What do these mean?': '这些是什么意思？',
  'Item options': '项目选项',
  'Service options': '服务选项',
  'Service Type': '服务类型',
  'Product Type': '商品类型',
  'Request process': '请求流程',
  'Commit after proposal': '提案后确认',
  'Commit at request': '请求即确认',

  /* ------------------------------------------------------------ 状态 */
  'Accepted': '已接受',
  'Completed': '已完成',
  'Pending': '待处理',
  'Draft': '草稿',
  'Hidden': '已隐藏',
  'Open': '开放',
  'Saved': '已保存',
  'Waitlist': '候补名单',
  'Waitlist Request': '候补请求',
  'Proposal': '提案',
  'Request': '请求',
  'My requests': '我的请求',
  'Revision': '修改',
  'Deliverable': '交付物',
  'Final Deliverable': '最终交付物',
  'Final Delivery': '最终交付',
  'Service': '服务',
  'Services': '服务',
  'Product': '商品',
  'Availability': '可接档期',
  'Confirmed and in queue': '已确认，排队中',
  'confirmed and in queue': '已确认，排队中',
  'Ready → WIP': '就绪 → 进行中',
  'Review period has ended': '评价期已结束',
  'Review period will end in 14 days': '评价期将在 14 天后结束',
  'My Requests in hidden categories will appear blurred, not hidden': '隐藏分类中的「我的请求」会显示为模糊，而非完全隐藏',
  'cancelled a Request': '取消了一个请求',
  'declined a Request': '拒绝了一个请求',

  /* ---------------------------------------------------- 徽章 / 身份 */
  'VGen Verified': 'VGen 认证',
  'VGen verified': 'VGen 认证',
  'Verified': '已认证',
  'Verified but private': '已认证但不公开',
  'Verified Media': '已认证素材',
  'Verified Portfolio Showcase': '已认证作品集展示',
  'Star Seller': '明星卖家',
  'Verified + Star Seller': '已认证 + 明星卖家',
  'VGen staff': 'VGen 官方成员',
  'VGen Helper': 'VGen 社区助手',
  'VGen Moderator': 'VGen 版主',
  'Retired mod': '已退休版主',
  'Early bird': '早鸟',
  'Artist Rating': '画师评分',
  'Trusted artist with a proven track record of quality work.': '作品质量有口皆碑、值得信赖的画师。',
  'Trusted Shopkeeper with a proven track record of quality products.': '商品质量有口皆碑、值得信赖的店主。',
  'One of the most experienced and top-rated artists on VGen.': 'VGen 上经验最丰富、评价最高的画师之一。',
  'One of VGen\'s earliest supporters.': 'VGen 最早的支持者之一。',
  'An official member of VGen\'s staff.': 'VGen 官方团队成员。',
  'Official VGen community helper.': 'VGen 官方社区助手。',
  'Official VGen community moderator, and verified artist.': 'VGen 官方社区版主，认证画师。',
  'Beta partner whose feedback and support helped bring VGen to life.': 'Beta 合作伙伴，其反馈与支持帮助 VGen 走到今天。',
  'Run by an organization that employs in-house artists+.': '由拥有内部画师+ 的机构运营。',

  /* ------------------------------------------------------ 通用 / 小控件 */
  'Yes': '是',
  'All': '全部',
  'None': '无',
  'Or': '或',
  'Other': '其他',
  'Cancel': '取消',
  'Undo': '撤销',
  'Blur': '模糊',
  'Unblur': '取消模糊',
  'Add': '添加',
  'Save': '保存',
  'Short': '短',
  'Simple': '简单',
  'Optional': '可选',
  'Customizable': '可定制',
  'Modular': '模块化',
  'Misc': '杂项',
  'Base': '基础版',
  'Bundle': '打包',
  'Pre-made': '预制',
  'New Custom Design': '新建自定义设计',
  'Custom design available': '可提供定制设计',
  'Ability to customize': '可自定义',
  'Limited customizations': '有限定制',
  'Existing reference sheet': '已有设定图',
  'Incomplete template': '不完整的模板',
  'Design only': '仅设计',
  'Design + extras': '设计 + 附加项',
  'For Existing Designs': '用于已有设计',
  '1 of a kind': '独一无二',
  'Newly created design': '全新设计',
  'Attributes': '属性',
  'Properties': '属性',
  'Characteristics': '特征',
  'Skill': '技能',
  'Level': '水平',
  'Length': '长度',
  'Volume': '音量',
  'Tempo': '节奏',
  'Orientation': '方向',
  'Platform': '平台',
  'Subject': '主体',
  'Software': '软件',
  'Gender': '性别',
  'References': '参考',
  'Reference Sheet': '设定图',
  'Final': '最终',
  'Deliverables': '交付物',
  'Description': '描述',
  'Details': '详情',
  'Overview': '概览',
  'Review': '评价',
  'Rating': '评分',
  'Report': '举报',
  'Share': '分享',
  'Copy': '复制',
  'Copied': '已复制',
  'Edit': '编辑',
  'Delete': '删除',
  'Remove': '移除',
  'Close': '关闭',
  'Next': '下一步',
  'Back': '返回',
  'Continue': '继续',
  'Submit': '提交',
  'Confirm': '确认',
  'Apply': '应用',
  'Clear': '清除',
  'Reset': '重置',
  'Loading...': '加载中…',
  'Nothing here yet': '这里还什么都没有',
  'Attention': '注意',
  'Error': '错误',
  'An Error Occurred!': '出错了！',
  'Uh oh... something went wrong': '哎呀……出问题了',
  'Editor encountered an error:': '编辑器遇到错误：',
  'This website requires JavaScript to function properly.': '本站需要启用 JavaScript 才能正常运行。',
  'When you get notifications, they\'ll show up here': '收到通知后会显示在这里',

  /* ------------------------------------------------------------ 页脚 */
  'Privacy Policy': '隐私政策',
  'Terms of Service': '服务条款',
  'FAQs': '常见问题',
  'How VGen works': 'VGen 如何运作',
  'Made for creators': '为创作者而做',
  'Commissions made easy': '让委托变得简单',
  'VGen | For the love of human creativity': 'VGen | 出于对人类创造力的热爱'

};
