/* ==========================================================================
 * 词库：第五轮（折扣编辑器等"要登录+点进去才出现"的页面）
 *
 * 来源：用户截图。这类页面（编辑器、向导、弹层）我挖 JS 也挖不全，
 * 因为文案可能来自服务端或懒加载 chunk —— 截图是最权威的来源。
 * ========================================================================== */

var DICT_ROUND5 = {

  /* ------------------------------------------------------ 折扣编辑器 */
  'Save draft': '保存草稿',
  'Discount value': '折扣额度',
  'Discount duration': '折扣时长',
  'Discount can be set up to 31 days.': '折扣最长可设置 31 天。',
  'Additional settings': '附加设置',
  'Apply to extra licensing fees': '适用于额外授权费用',
  'Apply to commission add-ons': '适用于委托附加项',
  'Items using discount': '使用该折扣的项目',
  'Add services': '添加服务',
  'Add products': '添加商品',
  'Choose percentage': '选择百分比',
  'New Sale': '新促销',
  'Start': '开始',
  'End': '结束',
  'Timezone': '时区',

  /* ------------------------------------------------------ 同类页面补漏 */
  'Save changes': '保存更改',
  'Save and publish': '保存并发布',
  'Save and close': '保存并关闭',
  'Discard': '放弃',
  'Discard changes': '放弃更改',
  'Unsaved changes': '未保存的更改',
  'Draft saved': '草稿已保存',
  'Status:': '状态：',
  'Edit in settings': '在设置中修改',
  'Add item': '添加项目',
  'Remove item': '移除项目',
  'Select all': '全选',
  'Deselect all': '取消全选',
  'Expand': '展开',
  'Collapse': '收起',
  'Enable': '启用',
  'Disable': '停用',
  'Enabled': '已启用',
  'Disabled': '已停用',
  'Optional': '可选',
  'Required field': '必填项',
  'This field is required': '此项为必填',
  'Search...': '搜索…',
  'No results': '无结果',
  'Loading': '加载中',
  'Retry': '重试',
  'Go back': '返回',
  'Back': '返回',
  'Next step': '下一步',
  'Previous step': '上一步',
  'Finish': '完成',
  'Submit': '提交',
  'Confirm': '确认',
  'Are you sure?': '确定吗？',
  'Yes, continue': '是，继续',
  'No, cancel': '不，取消',
  'Learn more': '了解更多',
  'View details': '查看详情',
  'Hide details': '隐藏详情',
  'Copy link': '复制链接',
  'Copied!': '已复制！',
  'Select a date': '选择日期',
  'Select a time': '选择时间',
  'Start date': '开始日期',
  'End date': '结束日期',
  'Start time': '开始时间',
  'End time': '结束时间',
  'Time zone': '时区',
  'Percentage': '百分比',
  'Fixed amount': '固定金额',
  'Amount': '金额',
  'Total': '合计',
  'Subtotal': '小计',
  'Tax': '税',
  'Fee': '费用',
  'Fees': '费用',
  'Net': '净额',
  'Gross': '总额',
  'Available': '可用',
  'Unavailable': '不可用',
  'Expires': '到期',
  'Never expires': '永不过期',
  'Valid until': '有效期至',
  'Usage': '使用情况',
  'Used': '已使用',
  'Unlimited': '无限制',
  'Limit': '上限',
  'Maximum': '最大',
  'Minimum': '最小',
  'Maximum 31 days': '最长 31 天',
  'per item': '每件',
  'per order': '每单',
  'per user': '每位用户',
  'All products': '所有商品',
  'All services': '所有服务',
  'Selected products': '已选商品',
  'Selected services': '已选服务',
  'Add a name': '填写名称',
  'Name is required': '名称为必填',
  'Description is required': '描述为必填'
};
