/* ==========================================================================
 * 词库 4/4：页面宣传语 / 分类描述长句
 * 这些出现在分类落地页和空状态提示里，句长、数量多，但一眼就能看出效果
 * ========================================================================== */

var DICT_COPY = {

  /* -------------------------------------------------- "宝库" 系列描述 */
  'A treasure trove of 2D vtuber model art creations!': '2D VTuber 模型美术作品的宝库！',
  'A treasure trove of creations to fill your world with joy.': '让你的世界充满欢乐的创作宝库。',
  'A treasure trove of services to bring your animation to life.': '让你的动画活起来的服务宝库。',
  'A treasure trove of services to get the perfect sound that you want!': '帮你得到理想声音的服务宝库！',
  'A treasure trove of words for your next project.': '为你的下一个项目准备的文字宝库。',
  'A treasure trove of 3D Character Models!': '3D 角色模型宝库！',
  'A treasure trove of 3D possibilities!': '3D 无限可能的宝库！',
  'A treasure trove of customizable and pre-made VTuber models!': '可定制与预制 VTuber 模型的宝库！',
  'A treasure trove of offerings to make your product stand out!': '让你的商品脱颖而出的服务宝库！',
  'A treasure trove of options to bring your videos to life.': '让你的视频活起来的方案宝库。',
  'A treasure trove of services to bring your next project to life!': '让你的下一个项目活起来的服务宝库！',
  'A treasure trove of songs, tracks, and amazing sounds.': '歌曲、音轨与惊艳音效的宝库。',
  'A treasure trove of unique reactive avatar creations!': '独特反应式头像作品的宝库！',
  'A treasure trove of voice talents for your next project.': '为你的下一个项目准备的声优宝库。',
  'A treasure trove of VRoid creations!': 'VRoid 作品的宝库！',
  'A treasure trove of VTuber model rigging creations!': 'VTuber 模型绑定作品的宝库！',
  'A trove of options to help build your brand!': '帮你打造品牌的方案宝库！',
  'A variety of graphic designs for any occasion and event!': '适用于各种场合与活动的多样平面设计！',
  'A little help to kickstart your animation skills~': '帮你起步动画技能的小小助力～',
  'A trove of assets to elevate your stream to the next level.': '让你的直播更上一层楼的素材宝库。',

  /* ---------------------------------------------------------- 引导语 */
  'Bring your 2D character into the 3D physical world!': '把你的 2D 角色带入 3D 现实世界！',
  'Bring your existing cute character and let\'s make them even cuter!': '带上你现有的可爱角色，让我们把它变得更可爱！',
  'Bring your characters to life through the magic of animation!': '用动画的魔法让你的角色活起来！',
  'Bring your video ideas to life.': '让你的视频创意成真。',
  'Bring your world to life through the magic of 3D modelling.': '用 3D 建模的魔法让你的世界活起来。',
  'Bring your reference sheet and let\'s bring your character to life!': '带上你的设定图，让我们把角色做活！',
  'Captivate listeners from the moment they lay eyes on your album!': '让人一眼看到专辑就被吸引！',
  'Captivate readers from the moment they lay eyes on your book!': '让人一眼看到书就被吸引！',
  'Catchy, iconic tunes to help you leave a lasting impression!': '抓耳又标志性的旋律，让人记住你！',
  'Chibi reactive avatars made for streaming, videos, and hanging out!': '为直播、视频和闲聊打造的 Q 版反应式头像！',
  'Custom frames so your creations are always consistent and on brand.': '自定义外框，让你的作品始终风格统一、契合品牌。',
  'Custom in-game skins to help you look like yourself in Minecraft!': '自定义游戏皮肤，让你在 Minecraft 里也是自己！',
  'Customizable and pre-made models to kickstart your VTubing journey ~': '可定制与预制模型，助你开启 VTubing 之旅～',
  'Customize your favorite games to look and feel like you!': '定制你喜欢的游戏，让它看起来像你！',
  'Customize and stand out with new accessories for your 2D model!': '用新配件定制你的 2D 模型，脱颖而出！',
  'Custom stickers that will stick a smile on your face~': '让你嘴角上扬的定制贴纸～',
  'Custom made in the physical world, created just for you.': '现实世界中的定制制作，只为你而做。',
  'Designed just for you, made with love, delivered to your door!': '为你而设计，用心制作，送到你家门口！',
  'Discover all the stories you won\'t be able to put down ~': '发现那些让你爱不释手的故事～',
  'Drawn artworks of any style': '各种风格的绘画作品',
  'Extend your immersion to your IRL stream setup!': '把你的沉浸感延伸到现实直播设备！',
  'Find templates to maximize your productivity! Now that\'s efficiency~': '找到让效率最大化的模板！这才叫高效～',
  'Fine-tune your 3D avatars to take them to the next level!': '微调你的 3D 头像，让它更上一层楼！',
  'Fine-tune your VRoid model to take them to the next level!': '微调你的 VRoid 模型，让它更上一层楼！',
  'From cuddly to terrifying, fill your world with 3D creatures!': '从萌到可怕，用 3D 生物填满你的世界！',
  'From food, fashion, props, cars, and more, bring your world to life!': '食物、时装、道具、车辆……让你的世界活起来！',
  'For the art, for the hugs, for the love of waifus and husbandos.': '为了艺术，为了拥抱，为了对纸片人的爱。',
  'For the games you love and the favs you just haven\'t discovered yet ~': '为你热爱的游戏，以及你还没发现的宝藏～',
  'For the love of human creativity': '出于对人类创造力的热爱',
  'Get it now before it\'s gone~': '趁还没下架，赶紧入手～',
  'Get noticed with thumbnails that viewers can\'t help but click into.': '用让人忍不住点进来的缩略图获得关注。',
  'Graphic design / Stream assets': '平面设计／直播素材',
  'Handmade goods, created just for you.': '手工制作，只为你而做。',
  'Help your product stand out with eye-catching packaging and labels!': '用吸睛的包装和标签让你的商品脱颖而出！',
  'Ideas are limitless, it\'s only a matter of getting them into words!': '创意无限，只差把它们写成文字！',
  'If you use a mouse, you\'ll need a mousepad. It\'s as simple as that.': '用鼠标就得有鼠标垫，就这么简单。',
  'Incredible voices to help bring your music to life~': '惊艳的歌声，让你的音乐活起来～',
  'It\'s nice to chat with people': '和人聊天真好',
  'It\'s time to become who you\'ve always wanted to be~': '是时候成为你一直想成为的样子了～',
  'It\'s time to make your profile b~e~a~u~t~i~f~u~l~~~': '是时候让你的主页美～起～来～了～～～',
  'Keychains, charms, and standees, take your charactes everywhere!': '钥匙扣、挂件和立牌，把你的角色带到任何地方！',
  'Let the devices you look at daily bring a smile to your face ~': '让每天看着的设备也让你会心一笑～',
  'Let your story unfold through the magic of words ~': '用文字的魔法展开你的故事～',
  'Let the world be filled with your unique songs and sounds ~': '让世界充满你独特的歌声与音色～',
  'Let\'s take a look back at your year on VGen~': '一起回顾你在 VGen 的这一年～',
  'Lil guys to keep you company on stream~': '陪你在直播里作伴的小家伙～',
  'Make the ultimate cozy game even cozier ~': '让最治愈的游戏更治愈～',
  'Memorable, iconic, and the cornerstone of your brand and being.': '令人难忘、标志性，是你品牌与存在的基石。',
  'No matter what the vibe, great music will make it even more special~': '无论什么氛围，好音乐都能让它更特别～',
  'One of a kind clothing and accessories, created just for you!': '独一无二的服装与配饰，只为你而做！',
  'One of a kind sculptures moulded and formed, just for you.': '独一无二的雕塑，为你塑形而成。',
  'Pets, mascots, and creatures for streaming, videos, and hanging out!': '陪你直播、拍视频和闲聊的宠物、吉祥物和生物！',
  'Promote, celebrate, and welcome your community to your upcoming event.': '为你的活动做宣传、庆祝，并迎接你的社区。',
  'Recognize and reward the ones who make your community incredible.': '认可并奖励那些让你的社区变得出色的人。',
  'Say hello to creatures from your wildest ideals and visions.': '向你最狂野构想中的生物打个招呼。',
  'Set the stage for your stories, creations, and worlds.': '为你的故事、创作和世界搭好舞台。',
  'Show off all of your model\'s best angles and toggles!': '展示你模型的每个最佳角度与开关！',
  'Show the world what your music looks like.': '让世界看到你音乐的样子。',
  'Software and tools to make game dev easier and more fun!': '让游戏开发更轻松、更有趣的软件与工具！',
  'Software and tools to make VTubing easier and more fun!': '让 VTubing 更轻松、更有趣的软件与工具！',
  'Song lyrics to match your melody and mood~': '契合你旋律与心情的歌词～',
  'Starting from scratch is hard, so why not start with a little help?': '从零开始很难，何不先借点力？',
  'Stunning fashion tailored just for your character!': '为你的角色量身打造的惊艳时装！',
  'Take your videos to the next level and make your viewers say WOW.': '让你的视频更上一层楼，让观众惊呼 WOW。',
  'Thank you for supporting human artists+': '感谢你支持人类画师+',
  'The perfect way to kickstart your empty Goodnotes pages!': '开启你空白 Goodnotes 页面的完美方式！',
  'The perfect way to kickstart your empty Google Sheets!': '开启你空白 Google 表格的完美方式！',
  'The perfect way to kickstart your empty Notion pages!': '开启你空白 Notion 页面的完美方式！',
  'There\'s nothing more immersive than the perfect background music~': '没有什么比完美的背景音乐更让人沉浸～',
  'Tools and apps to help make our lives more convenience and fun~': '让生活更便利、更有趣的工具和应用～',
  'Tools to make your workflow smoother and more fun~': '让你的工作流更顺畅、更有趣的工具～',
  'Transitions that\'ll make chat excited for what\'s coming up next.': '让观众对接下来充满期待的转场。',
  'Treat your eyes to something beautiful every time you log in~': '每次登录都能赏心悦目～',
  'Turn existing static emotes into animated delights.': '把现有静态表情变成会动的惊喜。',
  'Turn your audio tracks into perfectly blended and balanced music!': '把你的音轨变成完美融合、平衡的音乐！',
  'Turn your profile from bland to on-brand!': '让你的主页从平庸变得有品牌感！',
  'Unique audio effects to help you achieve the vibes you\'re looking for.': '独特的音效，帮你营造想要的氛围。',
  'Various add-ons that could take your 2D model to the next level!': '让你的 2D 模型更上一层楼的各种附加内容！',
  'Various add-ons to take your 3D model to the next level!': '让你的 3D 模型更上一层楼的各种附加内容！',
  'Welcome to the exciting world of VRChat and 3D VTuber Models~': '欢迎来到 VRChat 与 3D VTuber 模型的精彩世界～',
  'What would a [something that doesn\'t exist] look like? Let\'s find out.': '［不存在的东西］长什么样？我们来试试。',
  'What would something you envision look like animated? Let\'s find out.': '你构想的画面动起来会是什么样？我们来试试。',
  'Won\'t you adopt them and make them your own?': '不来领养它们，让它们成为你的吗？',
  'You can never have too many icon packs - says every designer ever~': '图标包永远不嫌多——每个设计师都这么说～',
  'You have an iPad / Tablet... why not make it pretty?': '你有 iPad／平板……何不让它好看点？',
  'You have characters and ideas... but what\'s going to happen next?': '你有角色和点子……但接下来会发生什么？',
  'You stare at your phone all day... why not make it pretty?': '你整天盯着手机……何不让它好看点？',
  'You stare at your screen all day... why not make it pretty?': '你整天盯着屏幕……何不让它好看点？',
  'You\'re on Tumblr - don\'t miss the opportunity to customize!!!': '你在用 Tumblr——别错过定制的机会！！！',
  'Your beautiful new website is right around the corner~': '你漂亮的新网站马上就来了～',
  'Your chibi persona brought to life through the magic of VRoid.': '用 VRoid 的魔法让你的 Q 版形象活起来。',
  'Your persona brought to life through the magic of VRoid.': '用 VRoid 的魔法让你的形象活起来。',
  'Your story, brought to life through illustrated panels ~': '用插画分镜让你的故事活起来～',
  'Your new fav game is waiting for you ~': '你新的最爱游戏在等你～',
  'Show the world what your music looks like.': '让世界看到你音乐的样子。',

  /* ------------------------------------------- 教程 / 咨询页的宣传语 */
  'Level up your 3D animation skills with step-by-step tutorials!': '用分步教程提升你的 3D 动画技能！',
  'Level up your 3D modelling skills with step-by-step tutorials!': '用分步教程提升你的 3D 建模技能！',
  'Level up your animation skills with step-by-step tutorials!': '用分步教程提升你的动画技能！',
  'Level up your audio engineering skills with step-by-step tutorials!': '用分步教程提升你的音频工程技能！',
  'Level up your coding skills with step-by-step tutorials!': '用分步教程提升你的编程技能！',
  'Level up your digital illustration skills with step-by-step tutorials!': '用分步教程提升你的数字插画技能！',
  'Level up your game mod skills with step-by-step tutorials!': '用分步教程提升你的游戏 Mod 技能！',
  'Level up your graphic design skills with step-by-step tutorials!': '用分步教程提升你的平面设计技能！',
  'Level up your Live2D rigging skills with step-by-step tutorials!': '用分步教程提升你的 Live2D 绑定技能！',
  'Level up your motion graphics skills with step-by-step tutorials!': '用分步教程提升你的动态图形技能！',
  'Level up your music production skills with step-by-step tutorials!': '用分步教程提升你的音乐制作技能！',
  'Level up your traditional art skills with step-by-step tutorials!': '用分步教程提升你的传统美术技能！',
  'Level up your UI / UX skills with step-by-step tutorials!': '用分步教程提升你的 UI／UX 技能！',
  'Level up your video editing skills with step-by-step tutorials!': '用分步教程提升你的视频剪辑技能！',
  'Level up your voice work skills with step-by-step tutorials!': '用分步教程提升你的配音技能！',

  'Want to improve your 3D animation skills? Get the help you need!': '想提升 3D 动画技能？来找你需要的帮助！',
  'Want to improve your 3D modelling skills? Get the help you need!': '想提升 3D 建模技能？来找你需要的帮助！',
  'Want to improve your audio engineering skills? Get the help you need!': '想提升音频工程技能？来找你需要的帮助！',
  'Want to improve your coding skills? Get the help you need!': '想提升编程技能？来找你需要的帮助！',
  'Want to improve your game modification skills? Get the help you need!': '想提升游戏 Mod 技能？来找你需要的帮助！',
  'Want to improve your graphic design skills? Get the help you need!': '想提升平面设计技能？来找你需要的帮助！',
  'Want to improve your motion graphics skills? Get the help you need!': '想提升动态图形技能？来找你需要的帮助！',
  'Want to improve your music production skills? Get the help you need!': '想提升音乐制作技能？来找你需要的帮助！',
  'Want to improve your rigging skills? Get the help you need!': '想提升绑定技能？来找你需要的帮助！',
  'Want to improve your streaming skills? Get the help you need!': '想提升直播技能？来找你需要的帮助！',
  'Want to improve your traditional arts skills? Get the help you need!': '想提升传统美术技能？来找你需要的帮助！',
  'Want to improve your UI / UX skills? Get the help you need!': '想提升 UI／UX 技能？来找你需要的帮助！',
  'Want to improve your video editing skills? Get the help you need!': '想提升视频剪辑技能？来找你需要的帮助！',
  'Want to improve your voice work skills? Get the help you need!': '想提升配音技能？来找你需要的帮助！',

  /* ------------------------------------------------------- 其它散句 */
  'Creative tools to help take your illustrations to the next level ~': '助你的插画更上一层楼的创作工具～',
  'Bring your characters to life through the magic of animation!': '用动画的魔法让你的角色活起来！',
  'Commissions made easy': '让委托变得简单',
  'Made for creators': '为创作者而做',
  'BGM, voice acting, song cover, etc': 'BGM、配音、翻唱等',
  'Emotes, overlays, stinger transitions, etc.': '表情、叠加层、转场等',
  'Pose, traits, multiple characters, add-ons, etc.': '姿势、特征、多角色、附加内容等',
  'Poses + References': '姿势 + 参考',
  'Items, props, and accessories to fill your 3D world.': '填满你 3D 世界的物品、道具与配件。',
  'Photoshoots and editing to make your vision come to life.': '用拍摄与修图让你的构想成真。'
};
