/* ==========================================================================
 * 词库：第四轮补漏（来自用户第二次导出的 1089 行清单）
 *
 * 这一轮收集器修复了「90 字符上限」和「丢弃全大写」两个 bug，
 * 所以清单长度翻倍，抓到了设置页、任务引导、钱包、服务表单的大量文案。
 *
 * 已剔除：画师名／用户名／服务标题，以及被 CSS 截断的碎片
 * （清单里那些 `Character Re` / `Cra` / `ect` / `rame-by-` 之类）。
 * ========================================================================== */

var DICT_ROUND4 = {

  /* ---------------------------------------------------- 任务 / 引导 */
  'Add 2 services': '添加 2 个服务',
  'Add 2 social links': '添加 2 个社交链接',
  'Add 5 portfolio showcases': '添加 5 个作品集展示',
  'Add a bio': '添加简介',
  'Add your VGen link to your Twitter bio / carrd / Instagram / Bluesky': '把你的 VGen 链接加到 Twitter 简介／Carrd／Instagram／Bluesky',
  'Commission Grand Opening': '委托盛大开业',
  'Complete your Shop Grand Opening quest to make your products visible in discovery + search!': '完成「商店盛大开业」任务，让你的商品出现在发现页和搜索中！',
  'Congratulations, you\'re live!': '恭喜，你已上线！',
  'Connect PayPal or VGen Payments': '连接 PayPal 或 VGen Payments',
  'Connect your showcases and services to help potential clients commission you easier': '关联你的作品集与服务，让潜在客户更容易委托你',
  'Create compelling content of your products by sharing behind the scenes / your products in-use / special offers to drive customers to your shop!': '通过分享幕后／商品使用中／特别优惠来制作吸引人的内容，把顾客带到你的商店！',
  'Dynamic guaranteed delivery': '动态保证交付',
  'Earn your badge, unlock unlimited services and showcases, invites, priority discovery, and more!': '获得你的徽章，解锁无限服务与作品集、邀请、优先推荐等！',
  'Earn your Star Seller badge, unlock unlimited shop listings, priority discovery to your profile, and more!*': '获得你的「明星卖家」徽章，解锁无限商店上架、主页优先推荐等！*',
  'Everything you need to start accepting requests!': '开始接受请求所需的一切！',
  'Everything you need to start taking orders!': '开始接单所需的一切！',
  'Get ready for commissions': '准备开始接委托',
  'Get ready for orders': '准备开始接单',
  'Get your Star': '获得你的星星',
  'Help clients find you': '帮客户找到你',
  'Help customers find you': '帮顾客找到你',
  'Let people find and access your shop easily to increase discovery!': '让人们更容易找到并访问你的商店，提升曝光！',
  'Leverage trends to create products / content in demand': '借助趋势创作有需求的商品／内容',
  'Link 2 portfolio showcases to existing service(s)': '关联 2 个作品集展示到已有服务',
  'Link relevant commission services': '关联相关的委托服务',
  'List 1 product': '上架 1 件商品',
  'Marketing 101: help people find your comms': '营销入门：让人找到你的委托',
  'Marketing 101: help people find your shop': '营销入门：让人找到你的商店',
  'Milestones, recommendations, and challenges to help you make the most of your adventures on VGen!': '里程碑、推荐与挑战，帮你在 VGen 的旅程中收获更多！',
  'Once you become a Star Seller, you must maintain certain requirements in order to keep your status.': '成为明星卖家后，你必须持续满足一定要求才能保有此身份。',
  'Optimize your product listings': '优化你的商品上架',
  'Pay attention to trends and market demands in your niche to create relevant and unique products~': '关注你所在领域的趋势与市场需求，创作相关且独特的商品～',
  'Post content on social media to increase shop engagement': '在社交媒体发布内容以提升商店互动',
  'See previous quests': '查看往期任务',
  'Share your shop link to your social bios and / or pinned posts': '把你的商店链接放到社交简介和／或置顶帖',
  'Shop Grand Opening': '商店盛大开业',
  'So people who are interested in custom versions of your products can find your services': '让对你的定制版商品感兴趣的人能找到你的服务',
  'Split out your portfolio showcases instead of bunching them into folders for maximum impact': '把作品集展示拆开，而不是塞进文件夹，以获得最大效果',
  'Tag all your products': '为所有商品加标签',
  'Tag all your services': '为所有服务加标签',
  'Tag all your showcases': '为所有作品集加标签',
  'This will help you get discovered once you go live!': '这有助于你在上线后被更多人发现！',
  'This will help you get discovered!': '这有助于你被更多人发现！',
  'To help more people off of VGen find your products': '帮更多 VGen 站外的人找到你的商品',
  'Update your profile banner': '更新你的主页横幅',
  'Update your profile picture': '更新你的主页头像',
  'Use relevant keywords and eye catching titles to make your listings more appealing and discoverable by your target audience!': '使用相关关键词和吸睛标题，让你的上架内容更吸引目标受众、更容易被发现！',
  'You completed the Quest:': '你完成了任务：',
  'You dropped this, king': '你掉了这个，王',
  'products discoverable on VGen.co': '商品在 VGen.co 上可被搜索到',
  'services discoverable on VGen.co': '服务在 VGen.co 上可被搜索到',

  /* -------------------------------------------------- 认证 / 敏感内容 */
  'All Verified Artists are manually reviewed by a member of our team. You must meet all five requirements to be eligible for verification. There are': '所有认证画师都由我们团队成员人工审核。你必须满足全部五项要求才有资格获得认证。还有',
  'COMMUNICATION': '沟通',
  'DEADLINES AND DELIVERY': '截止日期与交付',
  'REVISIONS': '修改',
  'How to tag Sensitive Content on VGen': '如何在 VGen 上标记敏感内容',
  'Make sure all sensitive content is properly tagged': '确保所有敏感内容都已正确标记',
  'Mark as Sensitive Content': '标记为敏感内容',
  'no fees associated with verification': '认证不收取任何费用',
  'Whether suggestive, sexual / nudity, violent / gore, or other triggers': '无论是暗示性、性／裸露、暴力／血腥，或其它触发内容',
  'We have a 3 strike system for improper tagging of sensitive content and / or product / showcases search tags. Please tag responsibly to avoid warnings, suspensions, and bans.': '对敏感内容标记及／或商品／作品集搜索标签的不当标注，我们实行三振制。请负责任地标注，以免受到警告、停权与封禁。',
  'We have a 3 strike system for improper tagging of sensitive content and / or service / showcases search tags. Please tag responsibly to avoid warnings, suspensions, and bans.': '对敏感内容标记及／或服务／作品集搜索标签的不当标注，我们实行三振制。请负责任地标注，以免受到警告、停权与封禁。',
  '(non-sexual)': '（非性相关）',
  'Respectful': '尊重他人',
  'Very responsive': '回复很及时',
  'Helpful feedback': '有帮助的评价',
  'Anonymize public review': '匿名公开评价',
  'Your feedback helps VGen become safer for everyone.': '你的反馈让 VGen 对每个人都更安全。',

  /* ------------------------------------------------------ 服务 / 表单 */
  'Accepted Terms': '已接受条款',
  'Clear requirements': '需求清晰',
  'Custom + Open communication': '定制 + 开放沟通',
  'Custom Inquiries': '定制咨询',
  'Custom Inquiry': '定制咨询',
  'Custom inquiry form': '定制咨询表单',
  'Difficulties:': '难点：',
  'Do you have a deadline for this project?': '这个项目有截止日期吗？',
  'Do you have a deadline?*': '你有截止日期吗？*',
  'How will you be using this commission?': '你会如何使用这次委托作品？',
  'How will you be using this commission?*': '你会如何使用这次委托作品？*',
  'Illustration Template': '插画模板',
  'Intro message': '开场消息',
  'Is your budget flexible?*': '你的预算有弹性吗？*',
  'Is your deadline flexible?*': '你的截止日期有弹性吗？*',
  'Major structural changes later will incur extra fees.': '之后若做重大结构调整将额外收费。',
  'May I publicly stream / share the work with credit?*': '我可以公开直播／分享作品并署名吗？*',
  'Max 8MB each. JPG, PNG, GIF, WEBP, MP3, WAV, FLAC, OGG, OPUS or YouTube links (public or unlisted). First 6 media displayed in preview. First 20 media displayed in service.': '单个最大 8MB。支持 JPG、PNG、GIF、WEBP、MP3、WAV、FLAC、OGG、OPUS 或 YouTube 链接（公开或不公开）。预览显示前 6 个素材，服务页显示前 20 个。',
  'Please remove any "payments must be in X currency"': '请移除任何「付款必须使用 X 货币」的表述',
  'Please send me your character reference sheets and briefly describe your ideas (e.g., canvas size, static or animated, background requirements).': '请把你的角色设定图发给我，并简要描述你的想法（例如画布尺寸、静态或动态、背景要求）。',
  'Please specify a currency.': '请指定一种货币。',
  'Request Form': '需求表单',
  'Requesting process': '请求流程',
  'Scope': '范围',
  'Standard Flow': '标准流程',
  'The artist is not required to deliver by the date you specified. Once they send you back a proposal, make sure the guaranteed delivery date fits with your timeline before accepting.': '画师没有义务在你指定的日期前交付。对方发回提案后，请在接受前确认保证交付日期符合你的时间安排。',
  'Use the following template or fill this box with whatever you\'d like. If you mention any prices in your description, it\'s recommended you add the currency to avoid confusions.': '使用以下模板，或在框中随意填写。如果你在描述中提到价格，建议注明货币以免混淆。',
  'What are the details of your project?*': '你的项目有哪些细节？*',
  'What is your budget?*': '你的预算是多少？*',
  'When you expect to start work': '你预计何时开始工作',
  'Save and publish Form': '保存并发布表单',
  'Form name': '表单名称',
  'Policy name': '政策名称',
  'Project name': '项目名称',
  'Name of tax': '税项名称',
  'New form': '新建表单',
  'New policy': '新建政策',
  'New workflow': '新建工作流',
  'New Service': '新建服务',
  'New bundle': '新建套餐',
  'New discount': '新建折扣',
  'Service settings': '服务设置',
  'References and files': '参考与文件',
  'References and files*': '参考与文件*',
  'Samples': '样例',
  'Extra info': '附加信息',
  'Header': '页眉',
  'Folder': '文件夹',
  'Folder:': '文件夹：',
  'Default folder: cannot delete': '默认文件夹：无法删除',
  'Default folder: cannot delete; hidden on profile if left empty': '默认文件夹：无法删除；留空则在主页上隐藏',
  'Currently hidden on profile': '目前在主页上隐藏',
  'In use': '使用中',
  'Not in use': '未使用',
  'Add existing': '添加已有',
  'Add new': '新建',
  'Create new': '新建',
  'Continue editing': '继续编辑',
  'Discard changes and leave': '放弃更改并离开',
  'Wait! You have unsaved changes!': '等等！你有未保存的更改！',
  'Reset to default': '重置为默认',
  'Reorder': '重新排序',
  'Prioritize': '优先处理',
  'Priority': '优先',
  'Publish': '发布',
  'Unpaid': '未付款',
  'Paid': '已付款',
  'Paid and locked in': '已付款并锁定',
  'Paid via PayPal': '通过 PayPal 付款',
  'Partially paid': '部分付款',
  'Fully paid': '已全额付款',
  'Processed': '已处理',
  'Processing': '处理中',
  'Locked': '已锁定',
  'Secret': '私密',
  'Discoverable': '可被搜索到',
  'To be released': '待发布',
  'Coming soon': '即将推出',
  'Not started': '未开始',
  'On-going': '进行中',
  'WIP': '进行中',
  'Pause': '暂停',
  'Decline': '拒绝',
  'Recommend': '推荐',
  'Refund': '退款',
  'Refunds': '退款',
  'Withdrawals': '提现',
  'Deposits': '定金',
  'Boosts': '助推',
  'Adjustments': '调整',
  'Payment status': '付款状态',
  'Total fees': '费用合计',
  'Total payout': '提现总额',
  'Your total payout after all fees': '扣除所有费用后的提现总额',
  'Service + payment processing fees': '服务费 + 支付处理费',
  'Tax amount': '税额',
  'Tax ID': '税号',
  'Project subtotal': '项目小计',
  'Price': '价格',
  'Request change': '请求变更',
  'Request extension': '请求延期',
  'Mark as done': '标记为完成',
  'Manage tags': '管理标签',
  'Tag character': '标记角色',
  'Tagline': '一句话简介',
  'Updates': '更新',
  'Upload file': '上传文件',
  'Download all files': '下载全部文件',
  'Download invoices': '下载发票',
  'Go to PayPal': '前往 PayPal',
  'View stats': '查看数据',
  'See more': '查看更多',
  'Looking for something else?': '在找别的？',
  'Get in touch!': '联系我们！',
  'Okay! Thank you!': '好的！谢谢！',
  'Setup required': '需要设置',
  'Action required': '需要操作',
  'I usually reply within 24-48 hours.': '我通常在 24-48 小时内回复。',
  'Active clients': '活跃客户',
  'All transactions': '全部交易',
  'All time': '全部时间',
  'Custom range': '自定义区间',
  'Last 3 months': '最近 3 个月',
  'Last 30 days': '最近 30 天',
  'Ascending': '升序',
  'Descending': '降序',
  'Filter by commission tag': '按委托标签筛选',
  'Filter by payment status': '按付款状态筛选',
  'Filter transaction status': '按交易状态筛选',
  'Filter transaction type': '按交易类型筛选',
  'Filter transactions within a date range': '按日期区间筛选交易',
  'No transactions yet': '还没有交易',
  'No orders yet. Let\'s change that!': '还没有订单。让我们改变这一点！',
  'Confirmed date': '已确认日期',
  'Guaranteed by': '保证交付于',
  'Guaranteed delivery': '保证交付',
  'Guaranteed Delivery has passed': '保证交付日期已过',
  'Client may request full refund after this date': '客户可在此日期后要求全额退款',
  'After this, and only if they request one, your client will be entitled to a full refund.': '此后，且仅在客户主动要求时，才有权获得全额退款。',
  'After tomorrow, and only if they request one, your client will be entitled to a full refund.': '明天之后，且仅在客户主动要求时，才有权获得全额退款。',
  'Rush order fees may apply.': '可能产生加急费用。',
  'Currency conversion fees may apply': '可能产生货币兑换费',
  'Client paid': '客户已付款',
  'Client details': '客户信息',
  'Client': '客户',
  'Non-VGen user': '非 VGen 用户',
  'Required for Guests': '访客必需',
  'Required for VGen Users': 'VGen 用户必需',
  'Required': '必需',
  'Notify followers on status change': '状态变更时通知关注者',
  'When changed to OPEN or WAITLIST': '当状态变更为「开放」或「候补」时',
  'They must not be SOLD OUT, UNLISTED, or DRAFT': '它们不能是「已售罄」「不公开列出」或「草稿」状态',
  'Paypal transactions are processed directly by PayPal. Go to PayPal to manage your funds.': 'PayPal 交易由 PayPal 直接处理。前往 PayPal 管理你的资金。',
  'With our payment system, your payout will be in your local currency no matter what clients choose to pay in - they\'ll be responsible for their own currency conversion fees.': '使用我们的支付系统，无论客户选择用什么货币付款，你的提现都会以本地货币结算——客户需自行承担汇率换算费用。',
  'Out': '缺货',
  'Use': '使用',
  'USE': '使用',
  'Pro': 'Pro',
  'Premium Delivery': '优先交付',
  'Slots': '名额',
  'Status': '状态',
  'Date': '日期',
  'Name': '名称',
  'End time': '结束时间',
  'Start time': '开始时间',
  'Estimated start': '预计开始',
  'Submission date': '提交日期',
  'Timeline': '时间线',
  'Past': '过去',
  'Future': '未来',
  'Issue': '问题',
  'and': '和',
  'in marketplace': '在市场中',
  'In service details': '在服务详情中',
  'For all services': '适用于所有服务',
  'Surprise me': '随机惊喜',
  'Choose 1': '选择 1 项',
  'Choose search category': '选择搜索分类',
  'Follow back': '回关',
  'followed you': '关注了你',
  'Copy client link to proposal': '复制提案的客户链接',
  'Display service stat': '显示服务数据',
  'Update payments': '更新付款',
  'VGen Payments': 'VGen Payments',
  'USD': 'USD',
  'MV': 'MV',
  'A great first impression is one of the most important factors when it comes to getting comm requests.': '第一印象是能否拿到委托请求最重要的因素之一。',
  'A picture of your art with a face is generally best (your art > your logo)': '通常用带脸的画作照片最好（你的作品 > 你的标志）',
  'If you do this and tag #VGenComm when sharing past comms and #VGen when opening comms, we may RT you!': '如果你这样做，并在分享过往委托时带上 #VGenComm、开启委托时带上 #VGen，我们可能会转发你！',
  'If you offer ANY illustration commissions, please make sure your profile picture and banner only includes illustrations CREATED BY YOU and not another artist unless they\'ve been properly credited.': '如果你提供任何插画委托，请确保你的头像和横幅只包含你本人创作的插画，而非其他画师的作品——除非已适当署名。',
  'Be sure to mark as WIP when you start': '开始工作时记得标记为「进行中」',
  'All of 2026': '2026 全年',
  '(15 reviews)': '（15 条评价）',
  'Used for 2 services': '已用于 2 个服务',
  'Thanks for leaving a review for redsflame': '感谢你为 redsflame 留下评价',
  'Payment from redsflame - COMM#74C2FZEUS36V-M1': '来自 redsflame 的付款 - COMM#74C2FZEUS36V-M1',
  'submitted a Request for Pixel Art Commission (Icons / Chibis / Illustrations)': '提交了对「像素画委托（图标／Q 版／插画）」的请求',
  'has confirmed their commission and it\'s now in your queue!': '已确认其委托，现在已在你的队列中！',
  'Be as thorough as you can so that takeez3 can give you an accurate proposal!': '请尽可能写得详细，这样 takeez3 才能给你准确的提案！',
  'Please send me your character reference sheets and briefly describe your ideas (e.g., canvas size, static or animated, background requirements).': '请把你的角色设定图发给我，并简要描述你的想法（例如画布尺寸、静态或动态、背景要求）。',

  /* ---------------------------------------------------------- 标签补充 */
  'pix art': '像素画',
  'minecraft': 'Minecraft',
  'Surprise Me': '随机惊喜',
  'Harmony Guides': 'Harmony 指南'
};
